version: 0.0
os: linux
files:
  - source: /
    destination: /java-app
hooks:
  ApplicationStop:
    - location: stop-jar.sh   
      timeout: 180 
  ApplicationStart:
    - location: run-jar.sh   
      timeout: 180
