version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
    - java -version
    - yum -y install maven
  build:
    commands:
    - mvn install
artifacts:
  files:
  - target/*.jar
  - ./*.sh
  - appspec.yml
  discard-paths: yes
