version: 0.2

phases:
  install:
    commands:
    - java -version
    - yum -y install maven
  build:
    commands:
    - mvn install
artifacts:
  files:
  - target/*.jar
  - ./*.sh
  - appspec.yml
  discard-paths: yes
