version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.342.b07-1.amzn2.0.1.x86_64"

phases:
  install:
    commands:
    - echo installing maven...
    - sudo yum install maven
  build:
    commands:
    - echo building the app
    - mvn install
artifacts:
  files:
  - target/*.jar
  - *.sh
  - appspec.yml
  discard-paths: yes
